---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://gateway:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
  - job_name: docker_logs 
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

  - job_name: nginx_access_today
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_access_today
          __path__: /var/log/nginx/access.log
  
  - job_name: nginx_access_old
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_access_old
          __path__: /var/log/nginx/access.log.1

  - job_name: nginx_error_today
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_error_today
          __path__: /var/log/nginx/error.log

  - job_name: nginx_error_old
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_error_old
          __path__: /var/log/nginx/error.log.1
