{
 "title": "DX Docker Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DX Client Docker Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"dx-dev\"}"
    }
   ]
  },
  {
   "title": "DX Server Docker Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"dx-server-dev\"}"
    }
   ]
  },
  {
   "title": "DX Backend Docker Logs",
   "type": "logs",
   "description": "DX Backend Docker Logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{container=\"dx-backend-dev\"}"
    }
   ]
  },
  {
   "title": "DX MongoDB Docker Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{container=\"dx-mongo-dev\"}"
    }
   ]
  }
 ]
}